# Generated by Django 3.2 on 2021-04-22 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Label Company Name')),
                ('founded_date', models.DateField(verbose_name='Founded Date')),
                ('headquarters', models.CharField(max_length=512, verbose_name='Location of Headquarters')),
            ],
        ),
    ]
