# Generated by Django 3.2 on 2021-04-22 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicDirector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name of the music director')),
                ('website', models.URLField()),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.CharField(max_length=13)),
            ],
        ),
    ]
