# Generated by Django 3.2 on 2021-04-22 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_musicdirector'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='slug',
            field=models.SlugField(default=None, null=True, verbose_name='URL param'),
        ),
        migrations.AddField(
            model_name='musicdirector',
            name='slug',
            field=models.SlugField(default=None, null=True, verbose_name='URL param'),
        ),
    ]
