# Generated by Django 3.2 on 2021-04-22 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Album Name')),
                ('subtitle', models.TextField(verbose_name='Description')),
                ('asin', models.CharField(max_length=10, verbose_name='Amazon Standard Indentification Number')),
                ('release_date', models.DateField()),
                ('cover_image', models.ImageField(null=True, upload_to='music/images')),
                ('genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.genre')),
                ('label', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.label')),
                ('music_director', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.musicdirector')),
            ],
        ),
    ]
