# Generated by Django 3.2 on 2021-04-22 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_album'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Album Name')),
                ('duration', models.DurationField(verbose_name='Duration of the song')),
                ('slug', models.SlugField(verbose_name='URL param')),
                ('album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.album')),
                ('genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.genre')),
                ('music_director', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.musicdirector')),
            ],
        ),
    ]
