# Generated by Django 3.2 on 2021-04-22 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_music'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='slug',
            field=models.SlugField(default=None, null=True, verbose_name='URL param'),
        ),
    ]
