# Generated by Django 3.2 on 2021-04-22 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_album_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Music Name'),
        ),
    ]
